apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-streamlit.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: streamlit
